//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominikGoralLab6Zad11
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Manufacturer { get; set; }
        public string Type { get; set; }
        public Nullable<int> Price { get; set; }
        public string Photo { get; set; }
    }
}
