//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DominikGoralLab6Zad11
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DominikGoralLab6Zad1_1Entities : DbContext
    {
        public DominikGoralLab6Zad1_1Entities()
            : base("name=DominikGoralLab6Zad1_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Furniture> Furniture { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
